component: cart-stage
service_type: ClusterIP
port: 80
container_port: 8080
target_port: 8080
PARAMETERS_ENABLED: true
PARAMETERS: "cart.stage.CATALOGUE_HOST_k,CATALOGUE_HOST cart.stage.CATALOGUE_PORT_k,CATALOGUE_PORT cart.stage.REDIS_HOST,REDIS_HOST"
env: stage

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi